### ISSUE TITLE
Things to improve before we work on AI

### ISSUE THREAD

**Issue by nivram108** [dream040102/Ewn#1]
- [x] Random
  srand seems not so random. I tried to run  a random AI hope to see different results. However I got the same result between two game which run time is pretty close. Hope you guys know what I'm talking about.
  ![image](https://cloud.githubusercontent.com/assets/16981817/19260469/64bd6e04-8fbc-11e6-9b71-a4a60543baff.png)
  You can see the same result between to games
- [ ] Clear unnecessary comments 
- [x] Color OuO?
- [x] Layout
  I think we should revise our layout. There should be a function includes selecting a chessman and making a single move, so it'll be easy for us to apply AI. Let's discuss the details together.

**Comment by tyhsu** [comment]
Layout的部分我是想說確定好普通玩家的play()以後在另外寫一個aiPlay()之類的啦～
可以禮拜四討論看看，我覺得應該都不難解決ˊˇˋ

**Comment by lichin-lin** [comment]
random: http://stackoverflow.com/questions/822323/how-to-generate-a-random-number-in-c/39475626#39475626
