### ISSUE TITLE
[ai] ai,game class architecture arrange

### ISSUE THREAD

**Issue by lichin-lin** [dream040102/Ewn#6]
## Things to modify

(1) ai class architecture
- [x] class-ai includes class-game? 👳
- [x] return movement to game.👰

(2) ai algorithm
- [x] minimax function👈

(3) game class architecture
- [x] movableChs改直接吃0~5，在建Movement前就先從movableChs知道要吃哪步棋
- [x] isLegal等函數因上面的movableChs要做修正
## Things to add on

(1) [class] game
- [x] game's  copy-constructor🙏🏿

**Comment by tyhsu** [comment]
class-ai includes class-game? 
=>> 要討論一下要新開一個member，還是直接在function裡做傳遞就好

**Comment by tyhsu** [comment]
class-ai includes class-game? 
👉 後來決定先用function傳遞
👉 autoPlay(Game, dice)         (註：autoPlay是原beforeMinimax)
👉👉👉 現在ai可以動了喔🎉🎉
