### ISSUE TITLE
Building minimax w/ chance node

### ISSUE THREAD

**Issue by nivram108** [dream040102/Ewn#7]
## play.cpp
- [x] Recover one game step
- [x] Control the game in a contest mode. ( We can assign the dice directly. the opponent choose a movement directly. )

## ewnAI.cpp
- [x]  Create a table for available moves   傳入<dice, chesses_exist>，得到<available_chess, available_chess>
- [x] miniMax: Get best value for each move for a chess, sum the possible chess' value.
- [x] bug: AI didn't select the assigned chess
<img width="326" alt="2016-11-19 9 26 28" src="https://cloud.githubusercontent.com/assets/17693695/20455865/e7a98694-ae5d-11e6-8b6e-cabf0600d7e8.png">

**Comment by tyhsu** [comment]
我修改了issue的內容喔
/
然後recover這個位置
為什麼不乾脆先判有沒有輸入z再決定要不要update board 這樣根本不需要複製Game什麼的啊＠＠
